packages:
  - package
  - dev-env
  - docs

linkWorkspacePackages: true
preferWorkspacePackages: true

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true

minimumReleaseAgeExclude:
  - vite@8.3.0
